// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/borrow" | "/docs" | "/faq" | "/faucet" | "/inscription/[id]" | "/markets" | "/markets/[pair]" | "/nft" | "/nft/claim" | "/order/[id]" | "/privacy" | "/stela/[id]" | "/swap" | "/terms" | "/trade"
type AppRouteHandlerRoutes = "/api/collateral-sales" | "/api/collateral-sales/[id]" | "/api/collection-offers" | "/api/collection-offers/[id]" | "/api/collection-offers/[id]/accept" | "/api/health" | "/api/inscriptions" | "/api/inscriptions/[id]" | "/api/inscriptions/[id]/events" | "/api/inscriptions/[id]/locker" | "/api/inscriptions/match" | "/api/lockers/[address]" | "/api/nft/collection/[address]" | "/api/nft/contract/[address]" | "/api/nft/owned/[owner]" | "/api/nft/token/[address]/[tokenId]" | "/api/nonce" | "/api/orders" | "/api/orders/[id]" | "/api/orders/[id]/offer" | "/api/orders/match" | "/api/pairs" | "/api/pairs/[pair]" | "/api/refinances" | "/api/refinances/[id]" | "/api/refinances/[id]/approve" | "/api/renegotiations" | "/api/renegotiations/[id]" | "/api/share-listings" | "/api/share-listings/[id]" | "/api/shares/[address]" | "/api/sync" | "/api/terms" | "/api/treasury/[address]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = "/genesis" | "/genesis/claim" | "/inscribe" | "/inscription/[id]" | "/order/[id]" | "/stelas"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/collateral-sales": {}
  "/api/collateral-sales/[id]": { "id": string; }
  "/api/collection-offers": {}
  "/api/collection-offers/[id]": { "id": string; }
  "/api/collection-offers/[id]/accept": { "id": string; }
  "/api/health": {}
  "/api/inscriptions": {}
  "/api/inscriptions/[id]": { "id": string; }
  "/api/inscriptions/[id]/events": { "id": string; }
  "/api/inscriptions/[id]/locker": { "id": string; }
  "/api/inscriptions/match": {}
  "/api/lockers/[address]": { "address": string; }
  "/api/nft/collection/[address]": { "address": string; }
  "/api/nft/contract/[address]": { "address": string; }
  "/api/nft/owned/[owner]": { "owner": string; }
  "/api/nft/token/[address]/[tokenId]": { "address": string; "tokenId": string; }
  "/api/nonce": {}
  "/api/orders": {}
  "/api/orders/[id]": { "id": string; }
  "/api/orders/[id]/offer": { "id": string; }
  "/api/orders/match": {}
  "/api/pairs": {}
  "/api/pairs/[pair]": { "pair": string; }
  "/api/refinances": {}
  "/api/refinances/[id]": { "id": string; }
  "/api/refinances/[id]/approve": { "id": string; }
  "/api/renegotiations": {}
  "/api/renegotiations/[id]": { "id": string; }
  "/api/share-listings": {}
  "/api/share-listings/[id]": { "id": string; }
  "/api/shares/[address]": { "address": string; }
  "/api/sync": {}
  "/api/terms": {}
  "/api/treasury/[address]": { "address": string; }
  "/borrow": {}
  "/docs": {}
  "/faq": {}
  "/faucet": {}
  "/genesis": {}
  "/genesis/claim": {}
  "/inscribe": {}
  "/inscription/[id]": { "id": string; }
  "/markets": {}
  "/markets/[pair]": { "pair": string; }
  "/nft": {}
  "/nft/claim": {}
  "/order/[id]": { "id": string; }
  "/privacy": {}
  "/stela/[id]": { "id": string; }
  "/stelas": {}
  "/swap": {}
  "/terms": {}
  "/trade": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
