// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/borrow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/borrow">> = Specific
  const handler = {} as typeof import("../../src/app/borrow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../src/app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../src/app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/faucet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faucet">> = Specific
  const handler = {} as typeof import("../../src/app/faucet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inscription/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inscription/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/inscription/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/markets/[pair]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/markets/[pair]">> = Specific
  const handler = {} as typeof import("../../src/app/markets/[pair]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/markets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/markets">> = Specific
  const handler = {} as typeof import("../../src/app/markets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/nft/claim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nft/claim">> = Specific
  const handler = {} as typeof import("../../src/app/nft/claim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/nft/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nft">> = Specific
  const handler = {} as typeof import("../../src/app/nft/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/order/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/order/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/order/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stela/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stela/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/stela/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/swap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/swap">> = Specific
  const handler = {} as typeof import("../../src/app/swap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/trade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trade">> = Specific
  const handler = {} as typeof import("../../src/app/trade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/collateral-sales/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/collateral-sales/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/collateral-sales/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/collateral-sales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/collateral-sales">> = Specific
  const handler = {} as typeof import("../../src/app/api/collateral-sales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/collection-offers/[id]/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/collection-offers/[id]/accept">> = Specific
  const handler = {} as typeof import("../../src/app/api/collection-offers/[id]/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/collection-offers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/collection-offers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/collection-offers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/collection-offers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/collection-offers">> = Specific
  const handler = {} as typeof import("../../src/app/api/collection-offers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inscriptions/[id]/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inscriptions/[id]/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/inscriptions/[id]/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inscriptions/[id]/locker/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inscriptions/[id]/locker">> = Specific
  const handler = {} as typeof import("../../src/app/api/inscriptions/[id]/locker/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inscriptions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inscriptions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/inscriptions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inscriptions/match/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inscriptions/match">> = Specific
  const handler = {} as typeof import("../../src/app/api/inscriptions/match/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inscriptions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/api/inscriptions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/lockers/[address]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lockers/[address]">> = Specific
  const handler = {} as typeof import("../../src/app/api/lockers/[address]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/nft/collection/[address]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nft/collection/[address]">> = Specific
  const handler = {} as typeof import("../../src/app/api/nft/collection/[address]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/nft/contract/[address]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nft/contract/[address]">> = Specific
  const handler = {} as typeof import("../../src/app/api/nft/contract/[address]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/nft/owned/[owner]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nft/owned/[owner]">> = Specific
  const handler = {} as typeof import("../../src/app/api/nft/owned/[owner]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/nft/token/[address]/[tokenId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nft/token/[address]/[tokenId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/nft/token/[address]/[tokenId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/nonce/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nonce">> = Specific
  const handler = {} as typeof import("../../src/app/api/nonce/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[id]/offer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/offer">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[id]/offer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/match/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/match">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/match/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pairs/[pair]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pairs/[pair]">> = Specific
  const handler = {} as typeof import("../../src/app/api/pairs/[pair]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pairs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pairs">> = Specific
  const handler = {} as typeof import("../../src/app/api/pairs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/refinances/[id]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/refinances/[id]/approve">> = Specific
  const handler = {} as typeof import("../../src/app/api/refinances/[id]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/refinances/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/refinances/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/refinances/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/refinances/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/refinances">> = Specific
  const handler = {} as typeof import("../../src/app/api/refinances/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/renegotiations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/renegotiations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/renegotiations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/renegotiations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/renegotiations">> = Specific
  const handler = {} as typeof import("../../src/app/api/renegotiations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/share-listings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/share-listings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/share-listings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/share-listings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/share-listings">> = Specific
  const handler = {} as typeof import("../../src/app/api/share-listings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/shares/[address]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shares/[address]">> = Specific
  const handler = {} as typeof import("../../src/app/api/shares/[address]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/terms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/terms">> = Specific
  const handler = {} as typeof import("../../src/app/api/terms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/treasury/[address]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/treasury/[address]">> = Specific
  const handler = {} as typeof import("../../src/app/api/treasury/[address]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
